import "./scss/globals.scss";
import { Poppins } from "next/font/google";
import PageLayout from "./pageLayout";

const poppins = Poppins({ weight: '400',
subsets: ['latin'], });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="layout">
          <div className="sidebar">
            <PageLayout />
          </div>
          <div className="mainBody">{children}</div>
        </div>
      </body>
    </html>
  );
}
